### ISSUE TITLE
Support cross-page conditions in multi-participant registrations

### ISSUE THREAD

**Issue by twomice** [twomice/com.joineryhq.profcond#12]
Use case:

In a multiple-participant online event registration:
- Price option A is selected for the primary (first) participant;
- Therefore, for the second (first additional) participant, we need price option B to be hidden.

Real-world example:
If the primary registrant selects the "Gold package", he should be able to select a discounted "banquet" option for any additional participants.

**Comment by andyburnsco** [comment]
This can be closed.

**Comment by twomice** [comment]
Thanks @andyburnsco !
