### ISSUE TITLE
No effect on Android Firefox or Tor browsers

### ISSUE THREAD

**Issue by andyburnsco** [twomice/com.joineryhq.profcond#13]
Conditionals that were setup have no effect while on an Android phone or in torbrowser. I receive this error when enabling debugging:

_Notice: Undefined index: all in .../wp-content/uploads/civicrm/ext/com.joineryhq.profcond/profcond.php on line 29_

The conditional selectors in question are checkboxes.

The conditionals work fine in Firefox, Chrome, Chromium.

**Comment by twomice** [comment]
Hi @andyburnsco . Just considering the size of TorBrower's userbase, it might be difficult for us to justify supporting it fully. Still, I'll take a look, see what we can find.  And of course I'm hopeful to support Android's Chrome browser.

In that light:
1. Am I understanding correctly that your conditionals are not working in the Android Chrome browser?
2. Could you provide a link to a public page where this bad behavior is visible?

**Comment by andyburnsco** [comment]
1. Correct
2. https://my.lp.org/2020-lnc-registration/

Agreed, Android is what matters. Just wanted to report all the cases where it didn't work.

**Comment by twomice** [comment]
Hi @andyburnsco Thanks for the link. Unfortunately (or fortunately?) I'm not able to reproduce the bad behavior, at least as I've understood it. See these two screenshots, which I hope target the relevant behavior: Gala Price is changing with selection of Basic Package vs No Package.

![Screenshot_20200527-140308](https://user-images.githubusercontent.com/759449/83061854-49c26e80-a023-11ea-8b25-3206c40d72be.png)

-----

![Screenshot_20200527-140316](https://user-images.githubusercontent.com/759449/83061856-49c26e80-a023-11ea-9a89-54bb017d2c57.png)

-----

Can you offer tips to help me reproduce the bad behavior?

**Comment by andyburnsco** [comment]
Looks like you are in iPhone? I can only reproduce on Android Firefox.

![Screenshot_20200527-143547_Firefox](https://user-images.githubusercontent.com/18341942/83064535-8b551880-a027-11ea-8ea5-d9259279b9d1.jpg)

All gala ticket options show on load of the page.

**Comment by twomice** [comment]
I'm on Android Chrome. Will try on Firefox.

**Comment by twomice** [comment]
Okay, I can reproduce on FF for Android; thanks for the clarification. 

Unfortunately, although I'm inclined to support the default mobile browsers (Chrome on Android; Safari on iPhone if possible), I'm not able to promise a fix for other mobile browsers on a community-contribution basis. If you'd like to sponsor a fix, please contact me by email. Thanks for understanding.

**Comment by twomice** [comment]
@andyburnsco We see a very similar issue for IE browser in #11, and [this comment](https://github.com/twomice/com.joineryhq.profcond/issues/11#issuecomment-658922091) indicates that problem is resolved in version 1.5-rc1.  Could you perhaps try that version and see if the problem is resolved?

**Comment by andyburnsco** [comment]
Tested 1.5 and works on Android Firefox and IE 11 desktop.
