### ISSUE TITLE
Support for custom contact fields

### ISSUE THREAD

**Issue by andrewr78** [twomice/com.joineryhq.profcond#17]
Hi :-)

I'm looking to add conditional fields to a custom contact record - (ie see atached (if condition = x then display y)) - I hope the attached mock up makes sense. 

Is this possible to do? 

tia,

Andrew

![2018-08-02 06_38_11-Mrs  dfg dfgd _ Ashfield RSL Sub-Branch - Opera](https://user-images.githubusercontent.com/41606603/94084239-63948680-fe48-11ea-8134-7fbf2e21e4f0.png)

**Comment by twomice** [comment]
Hi Andrew. Profile Conditionals works on front-end contribution forms and event registration pages. From your mockup, this appears to be a back-end form, maybe in CiviCase? In that case, this extension won't do anything in such forms. It's conceivable that it could be modified to do so, but we'd need to learn more about the use case and the business requirements before deciding about that.

On front-end contribution pages and event registration forms, this is definitely possible, though you'd need some careful thinking about how to construct the profile fields, and how to make Profile Conditionals aware of the correct values. I suppose it also depends on what you're doing with that URL value: Just need it to be stored as the value of a single custom field? Need to display a clickable link to that URL, or redirect to it? Such shades would inform how you structure the profile and implement the Profile Conditionals rules.

**Comment by twomice** [comment]
Closing for now. Please re-open if more help is needed.
