### ISSUE TITLE
How get a value for a date picker element ?

### ISSUE THREAD

**Issue by wyde22** [twomice/com.joineryhq.profcond#34]
Hi,

Sorry i have got another question. For my usecase, i want to get a value of date picker element. If my user have a birth date minor that specific date, i want to show element. Here my code

```
'4_mineur' => array(
            'conditions' => array(
              'all_of' => array(
                array(
                  'id' => 'birth_date', // 
                  'op' => 'value_gt',
                  'value' => strtotime('09/01/2005')
                ),
              )
            ),
            'states' => array(
              'pass' => array (
                'selectors' => array (
                  '#editrow-custom_32' => array(
                    'display' => 'show',
                  ),
                  '#editrow-custom_33' => array(
                    'display' => 'show',
                  ),
                  '#editrow-custom_34' => array( 
                    'display' => 'hide',
                  ),
                ),
              ),
              'fail' => array(
                'selectors' => array(
                  '#editrow-custom_32' => array(
                    'display' => 'hide',
                  ),
                  '#editrow-custom_33' => array(
                    'display' => 'hide',
                  ),
                  '#editrow-custom_34' => array( 
                    'display' => 'hide',
                  ),
                ),
              ),
            ),
          ),
```

here my HTML

```
<div class="crm-section editrow_birth_date-section form-item" id="editrow-birth_date">
        <div class="label">
          <label for="birth_date">  Date de naissance
          <span class="crm-marker" title="Ce champ est obligatoire.">*</span></label>
        </div>
    <div class="content">
          
        <span class="crm-form-date-wrapper"><input minyear="1923" maxyear="2023" format="mm/dd/yy" data-crm-datepicker="{&quot;date&quot;:&quot;mm\/dd\/yy&quot;,&quot;time&quot;:false,&quot;minDate&quot;:&quot;1923-07-14&quot;,&quot;maxDate&quot;:&quot;2023-07-14&quot;}" aria-label="Date de naissance" name="birth_date" type="text" id="birth_date" class="crm-form-text required crm-hidden-date profcond-has-rule_4_mineur" style="display: none;"><input type="text" class="crm-form-text required crm-form-date hasDatepicker crm-placeholder-icon" aria-label="Date de naissance" id="dp1689328356387" placeholder=""></span>
                      
     </div>
     <div class="clear"></div>
</div>
```
on load of page my element is hide with your extension

thanks

**Comment by twomice** [comment]
> i want to get a value of date picker element. If my user have a birth date minor that specific date, i want to show element.

Another way to say this is:  Is there an operator (see [[operator]](https://github.com/twomice/com.joineryhq.profcond#operator)) that will allow me to test whether the value of a date field is less than a specific date?

At present, the answer is no. The comparison operators currently available are:
- value_gt: The subject of [subject-identifier] must have a value which is greater than the given [test-value] values for the condition to pass (uses JavaScript > operator, expects to compare numeric values).
- value_gte: The subject of [subject-identifier] must have a value which is greater than or equal to the given [test-value] values for the condition to pass (uses JavaScript >= operator, expects to compare numeric values).
- value_lt: The subject of [subject-identifier] must have a value which is less than the given [test-value] values for the condition to pass (uses JavaScript < operator, expects to compare numeric values).
- value_lte: The subject of [subject-identifier] must have a value which is less than or equal to the given [test-value] values for the condition to pass (uses JavaScript <= operator, expects to compare numeric values).

You can see that all of those comparisons say "expects to compare numeric values", but the value of a date field will be a string in the format 'YYYY-MM-DD' (and sometimes it will be 'YYYY-MM-DD HH:MM:SS'.

These operators are unable to treat these values like dates, so the comparison will not work as you wish.

I'm open to the idea of adding more operators to support date comparisons, such as these:
- date_is
- date_gt
- date_gte
- date_lt
- date_lte

But at present they don't exist.

**Comment by wyde22** [comment]
ok thanks

for my date on my form i used a `strtotime` then transform string date on numeric values (timestamp) but it doesn't work
