### ISSUE TITLE
The user changes a value in the field, how are formerly displayed conditional fields (and hidden after the change) set to null

### ISSUE THREAD

**Issue by Guydn** [twomice/com.joineryhq.profcond#35]
Small example
There are 4 fields A, B, C, D
C and D are displayed if A = 1
B is displayed if A= 2
If the user input 1 in A, set values for C and D, and afterwards decides to input 2 in A, values in C and D are kept. 
What would be the best practice to "clean" or reset all fields that are hidden eventually. Including Priceset lines ?

**Comment by twomice** [comment]
You can use the 'value' [[state-property]](https://github.com/twomice/com.joineryhq.profcond#state-property) to change the value of a field. 

In this case, it sounds like you want to set the value to `''` (empty string), or perhaps to `'0'`.

For example, this would set the value to `''` (empty string) after hiding fields C and D:

```php
$rules = array(
  'rule_001' => array(
    'conditions' => array(
      // If value of field A == 1.
    ),
    'states' => array(
      'pass' => array (
        'selectors' => array(
          'field C selector, field D selector' => array(
            'display' => 'show',
          ),
        ),
      ),
      'fail' => array(
        'selectors' => array(
          'field C selector, field D selector' => array(
            'display' => 'hide',
            'value' => '', // empty the field
          ),
        ),
      ),
    ),
  ),
);
```

I hope this helps and will close the ticket now, but pleaes re-open if you need more help.

**Comment by twomice** [comment]
One more thing:

If B, C and D are price fields, you'll probably want to use the 'is_price_change' [[state-property]](https://github.com/twomice/com.joineryhq.profcond#state-property) to be sure that the total price is updated correctly.

**Comment by Guydn** [comment]
Thanks a lot  for your quick answer :-).
Guy (Nadaillac)
