### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by MegaphoneJon** [twomice/com.joineryhq.profcond#9]
I saw in the docs just now that there's no support for wildcards, which I thought was odd, because I *do* have the ability to specify conditionals to appear on all pages.  Seems like I have some uncontributed code I never posted to my Github fork!  I'm gonna take a look at what else I might have in here and make a PR or two.

**Comment by MegaphoneJon** [comment]
I have a fork that I've been meaning to merge back for ages.  Seeing the new release today reminded me.  Wildcards are supported (well - an "all" events or contribution pages) along with the ability to select an element by its label (helpful when using wildcards where an "Other" price option might have a different element name)

**Comment by twomice** [comment]
That sounds great, @MegaphoneJon . PR welcome any time.

**Comment by andrewr78** [comment]
Is it possible to have conditionals display custom fields for a contact?

IF condition = snake bite
  Then = display a url for animal envenomation

That sort of thing? - Is that possible?

**Comment by twomice** [comment]
(@andrewr78 That's off-topic to this thread, but yes it's possible. Please create a separate issue if you'd like to ask more about it. Thanks!)

**Comment by twomice** [comment]
Closing, as this was addressed in a33e3b786b6a95024691f6d80d26191d708f5ff8
